set shell=/bin/bash

set rtp+=/opt/homebrew/opt/fzf

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'gmarik/Vundle.vim' "Plug-in Management

Plugin 'nanotech/jellybeans.vim' " vim thema skin

Plugin 'neoclide/coc.nvim', {'branch': 'release'} "CocInstall

Plugin 'scrooloose/nerdtree' "file system explorer

Plugin 'vim-airline/vim-airline' " vim status bar
Plugin 'vim-airline/vim-airline-themes' " airline_themes
Plugin 'blueyed/vim-diminactive' "to dim inactive windows
Plugin 'talek/obvious-resize' "Obvious Resize_Windows

Plugin 'junegunn/vim-easy-align' "Vim alignment plugin.
Plugin 'nathanaelkane/vim-indent-guides' "visually displaying indent levels in Vim
Plugin 'townk/vim-autoclose'  " automatic closing of parentheses
Plugin 'luochen1990/rainbow' "colorful brackets.

Plugin 'matchparenpp'         " check parentheses.
Plugin 'ycm-core/YouCompleteMe' "automatic_completion

Plugin 'rust-lang/rust.vim' "rust
Plugin 'fannheyward/coc-rust-analyzer' "rust_analyzer
Plugin 'mattn/vim-lsp-settings' "rust_analyzer__lsp
Plugin 'liuchengxu/vista.vim' "Vista rust ctag
Plugin 'prabirshrestha/vim-lsp' 
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'

" haskell
Plugin 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': './install.sh'
    \ }


call vundle#end()

" rust InlayHint color setting
hi CocInlayHint guibg=Red guifg=Blue ctermbg=Red ctermfg=Blue
" Others hint
hi default CocRustChainingHint guibg=Red guifg=Blue ctermbg=0 ctermfg=18
